services:
  ddns:
    image: vinpogo/namecheap-ddns:latest
    container_name: namecheap-ddns
    restart: unless-stopped
    environment:
        - HOSTS=<YOUR HOSTS>
        - DOMAIN=<YOUR DOMAIN>
        - PASSWORD_FILE=/run/secrets/ddns-password
    secrets:
        - ddns-password

secrets:
  ddns-password:
    file: <PATH TO YOUR SECRET>
