services:
  ddns:
    image: vinpogo/namecheap-ddns:latest
    container_name: namecheap-ddns
    restart: unless-stopped
    environment:
        - HOST=<YOUR HOST>
        - DOMAIN=<YOUR DOMAIN>
        - PASSWORD=<YOUR API SECRET>
